import { Sales } from "./sale";


export const SALES: Sales[] = [
	{
		id: 1,
		customers: '1770-Al Karam',
        region: "Lahore,Punjab",
		date: "06/08/24",
		confirmDate: "07/08/24",
        status: "Close",
        quantity: 25,
        amount: 345,
        preparedBy: "Rich",
        approvedBy: "Anderson",
	},
	{
		id: 2,
        customers: '1771-Al Karam',
        region: "Lahore,Punjab",
		date: "23/08/22",
		confirmDate: "07/10/24",
        status: "New",
        quantity: 67,
        amount: 12345,
        preparedBy: "Rich",
        approvedBy: "Anderson",
	},
	{
		id: 3,
        customers: '1772-Al Karam',
        region: "Lahore,Punjab",
		date: "06/08/24",
		confirmDate: "07/08/24",
        status: "Close",
        quantity: 25,
        amount: 345,
        preparedBy: "Dany",
        approvedBy: "Blew",
	},
	{
		id: 4,
        customers: '1774-Al Karam',
        region: "Lahore,Punjab",
		date: "06/08/24",
		confirmDate: "07/08/24",
        status: "Void",
        quantity: 25,
        amount: 345,
        preparedBy: "Rich",
        approvedBy: "Anderson",
	},
	{
		id: 5,
        customers: '1777-Al Karam',
        region: "Lahore,Punjab",
		date: "06/08/24",
		confirmDate: "07/08/24", 
        status: "Dispatch",
        quantity: 25,
        amount: 345,
        preparedBy: "Rich",
        approvedBy: "Anderson",
	},
	
	
];